FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .

RUN dotnet restore ./FiatClient/FiatChamp.csproj
RUN dotnet publish ./FiatClient/FiatChamp.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app
COPY --from=build /out/ ./

ENTRYPOINT ["dotnet", "FiatChamp.dll"]
